# config/fixed/3d/gewei/sha_2.yaml
#  独立玩法推荐取值策略配置
# === 定位杀号位置 ===
DINGWEI_SHA_POS: 2

QUERY_PLAYTYPE_NAME: 定位5*5*5-个位
ANALYZE_PLAYTYPE_NAME: 定位5*5*5-个位

# === 回溯期数 ===
LOOKBACK_N: None

# === 命中条件 ===
HIT_RANK_LIST: [1,2,3]

# === 取值配置 ===
ENABLE_DINGWEI_SHA: [6]
FILTER_LAST_HIT: False     #true
# ✅ 推荐数少于5时跳过行为
#SKIP_IF_FEW_DINGWEI_SHA: True

# ✅ 控制每个策略的“频次并列”行为
#RESOLVE_TIE_MODE_DINGWEI_SHA: Next

# ✅ 并列频次触发反向提取控制项
#REVERSE_ON_TIE_DINGWEI_SHA: True