# config/fixed/3d/gewei/sha_2.yaml
#  独立玩法推荐取值策略配置
# === 定位杀号位置 ===
DINGWEI_SHA_POS: 2

QUERY_PLAYTYPE_NAME: 个位定3
ANALYZE_PLAYTYPE_NAME: 个位定3

# === 回溯期数 ===
LOOKBACK_N: 2

# === 命中条件 ===
HIT_RANK_LIST: [1]

# === 取值配置 ===
ENABLE_DINGWEI_SHA: [5]
