#  config/fixed/3d/base.yaml
# === 通用默认 ===
CHECK_MODE: dingwei
LOTTERY_NAME: 福彩3D
ANALYSIS_MODE: rank

# === 全期命中验证模式 ===
# ENABLE_HIT_CHECK: True
# ENABLE_TRACK_OPEN_RANK: True
# LOG_SAVE_MODE: True
# ALL_MODE_LIMIT: None

# === 最新一期跑结果模式 ===
ENABLE_HIT_CHECK: False
ENABLE_TRACK_OPEN_RANK: False
LOG_SAVE_MODE: False
ALL_MODE_LIMIT: 1


QUERY_ISSUES: All
LOOKBACK_N: 1

# === 通用启用开关，默认都 False ===
ENABLE_SHA1: False
ENABLE_SHA2: False
ENABLE_DAN1: False
ENABLE_DAN2: False
ENABLE_DINGWEI_SHA: False
ENABLE_DINGWEI_SHA2: False
ENABLE_DINGWEI_SHA3: False
ENABLE_DINGWEI_DAN1: False

# === 通用跳过条件 ===
SKIP_IF_FEW_SHA1: False
SKIP_IF_FEW_SHA2: False
SKIP_IF_FEW_DAN1: False
SKIP_IF_FEW_DAN2: False
SKIP_IF_FEW_DINGWEI_SHA: False
SKIP_IF_FEW_DINGWEI_SHA2: False
SKIP_IF_FEW_DINGWEI_SHA3: False

# === 通用并列处理 ===
RESOLVE_TIE_MODE_SHA1: False
RESOLVE_TIE_MODE_SHA2: False
RESOLVE_TIE_MODE_DAN1: False
RESOLVE_TIE_MODE_DAN2: False
RESOLVE_TIE_MODE_DINGWEI_SHA: False
RESOLVE_TIE_MODE_DINGWEI_SHA2: False
RESOLVE_TIE_MODE_DINGWEI_SHA3: False
RESOLVE_TIE_MODE_DINGWEI_DAN1: False

# === 通用反向处理 ===
REVERSE_ON_TIE_DINGWEI_SHA: False
REVERSE_ON_TIE_DINGWEI_SHA2: False
REVERSE_ON_TIE_DINGWEI_SHA3: False
REVERSE_ON_TIE_DINGWEI_DAN1: False

# === 默认玩法示例 ===
QUERY_PLAYTYPE_NAME: 百位定1
ANALYZE_PLAYTYPE_NAME: 百位定1

# === 命中条件示例 ===
HIT_RANK_LIST: [1]
HIT_COUNT_CONDITIONS: {}
