DEFAULTS:
  LOTTERY_NAME: 福彩3D
  ANALYSIS_MODE: rank
  QUERY_ISSUES: All
  ALL_MODE_LIMIT: None
  ENABLE_HIT_CHECK: True
  ENABLE_TRACK_OPEN_RANK: True
  LOG_SAVE_MODE: True

  SKIP_IF_FEW_SHA1: False
  SKIP_IF_FEW_SHA2: False
  SKIP_IF_FEW_DAN1: False
  SKIP_IF_FEW_DAN2: False
  SKIP_IF_FEW_DINGWEI_SHA: False
  SKIP_IF_FEW_DINGWEI_SHA2: False
  SKIP_IF_FEW_DINGWEI_SHA3: False

  RESOLVE_TIE_MODE_SHA1: False
  RESOLVE_TIE_MODE_SHA2: False
  RESOLVE_TIE_MODE_DAN1: False
  RESOLVE_TIE_MODE_DAN2: False
  RESOLVE_TIE_MODE_DINGWEI_SHA: False
  RESOLVE_TIE_MODE_DINGWEI_SHA2: False
  RESOLVE_TIE_MODE_DINGWEI_SHA3: False
  RESOLVE_TIE_MODE_DINGWEI_DAN1: False

  REVERSE_ON_TIE_DINGWEI_SHA: False
  REVERSE_ON_TIE_DINGWEI_SHA2: False
  REVERSE_ON_TIE_DINGWEI_SHA3: False
  REVERSE_ON_TIE_DINGWEI_DAN1: False

  ENABLE_SHA2: False
  ENABLE_DAN2: False
  ENABLE_DINGWEI_SHA2: False
  ENABLE_DINGWEI_SHA3: False
