# === 通用默认 ===
CHECK_MODE: dingwei
LOTTERY_NAME: 福彩3D
ANALYSIS_MODE: rank

ENABLE_HIT_CHECK: false
ENABLE_TRACK_OPEN_RANK: false
LOG_SAVE_MODE: false

ALL_MODE_LIMIT: 1
QUERY_ISSUES: All
LOOKBACK_N: 0

# === 通用启用开关，默认都 false ===
ENABLE_SHA1: false
ENABLE_SHA2: false
ENABLE_DAN1: false
ENABLE_DAN2: false
ENABLE_DINGWEI_SHA: false
ENABLE_DINGWEI_SHA2: false
ENABLE_DINGWEI_SHA3: false
ENABLE_DINGWEI_DAN1: false

# === 通用跳过条件 ===
SKIP_IF_FEW_SHA1: false
SKIP_IF_FEW_SHA2: false
SKIP_IF_FEW_DAN1: false
SKIP_IF_FEW_DAN2: false
SKIP_IF_FEW_DINGWEI_SHA: false
SKIP_IF_FEW_DINGWEI_SHA2: false
SKIP_IF_FEW_DINGWEI_SHA3: false

# === 通用并列处理 ===
RESOLVE_TIE_MODE_SHA1: False
RESOLVE_TIE_MODE_SHA2: False
RESOLVE_TIE_MODE_DAN1: False
RESOLVE_TIE_MODE_DAN2: False
RESOLVE_TIE_MODE_DINGWEI_SHA: False
RESOLVE_TIE_MODE_DINGWEI_SHA2: False
RESOLVE_TIE_MODE_DINGWEI_SHA3: False
RESOLVE_TIE_MODE_DINGWEI_DAN1: False

# === 通用反向处理 ===
REVERSE_ON_TIE_DINGWEI_SHA: false
REVERSE_ON_TIE_DINGWEI_SHA2: false
REVERSE_ON_TIE_DINGWEI_SHA3: false
REVERSE_ON_TIE_DINGWEI_DAN1: false

# === 默认玩法示例 ===
QUERY_PLAYTYPE_NAME: 百位定1
ANALYZE_PLAYTYPE_NAME: 百位定1

# === 命中条件示例 ===
HIT_RANK_LIST: [1]
HIT_COUNT_CONDITIONS: {}
