# config/fixed/3d/gewei/sha_2.yaml
#  独立玩法推荐取值策略配置
# === 定位杀号位置 ===
#ANALYSIS_MODE: hitcount
DINGWEI_SHA_POS: 1

QUERY_PLAYTYPE_NAME: 十位定1
ANALYZE_PLAYTYPE_NAME: 十位定1

# === 回溯期数 ===
LOOKBACK_N: 2

# === 命中条件 ===
HIT_RANK_LIST: [4]
#HIT_COUNT_CONDITIONS: {"十位定1": ("==", 0)}

# === 取值配置 ===
ENABLE_DINGWEI_SHA: ["prev+3,1"]

# ✅ 推荐数少于5时跳过行为
#SKIP_IF_FEW_DINGWEI_SHA: True

# ✅ 控制每个策略的“频次并列”行为
#RESOLVE_TIE_MODE_DINGWEI_SHA: True