# config/fixed/3d/gewei/sha_2.yaml
#  独立玩法推荐取值策略配置
# === 定位杀号位置 ===
#ANALYSIS_MODE: hitcount
DINGWEI_SHA_POS: 1

QUERY_PLAYTYPE_NAME: 十位定3
ANALYZE_PLAYTYPE_NAME: 十位定3

# === 回溯期数 ===
LOOKBACK_N: 1

# === 命中条件 ===
HIT_RANK_LIST: [-2]
#HIT_COUNT_CONDITIONS: {"十位定1": ("==", 0)}

# === 取值配置 ===
ENABLE_DINGWEI_SHA: [7]
