name: 排列5 -策略分析

on:
  workflow_dispatch:
    inputs:
      CHECK_MODE:
        description: "位置判断模式"
        required: true
        default: "dingwei"
        type: choice
        options: [dingwei, all]

      DINGWEI_SHA_POS:
        description: "定位位置（0=万位, 1=千位, 2=百位, 3=十位, 4=个位）"
        required: true
        default: "0"
        type: choice
        options: ["0", "1", "2", "3", "4"]


      QUERY_PLAYTYPE_NAME:
        description: "分析玩法"
        required: true
        default: "万位杀1"
        type: choice
        options:
          - "个位杀3"
          - "十位杀3"
          - "百位杀3"
          - "千位杀3"
          - "万位杀3"
          - "个位杀1"
          - "十位杀1"
          - "百位杀1"
          - "千位杀1"
          - "万位杀1"
          - "个位定5"
          - "十位定5"
          - "百位定5"
          - "千位定5"
          - "万位定5"
          - "百位定3"
          - "十位定3"
          - "个位定3"
          - "百位定1"
          - "十位定1"
          - "个位定1"
          - "千位定1"
          - "万位定1"
          - "千位定3"
          - "万位定3"


      ANALYZE_PLAYTYPE_NAME:
        description: "回溯玩法"
        required: true
        default: "万位杀1"
        type: choice
        options:
          - "个位杀3"
          - "十位杀3"
          - "百位杀3"
          - "千位杀3"
          - "万位杀3"
          - "个位杀1"
          - "十位杀1"
          - "百位杀1"
          - "千位杀1"
          - "万位杀1"
          - "个位定5"
          - "十位定5"
          - "百位定5"
          - "千位定5"
          - "万位定5"
          - "百位定3"
          - "十位定3"
          - "个位定3"
          - "百位定1"
          - "十位定1"
          - "个位定1"
          - "千位定1"
          - "万位定1"
          - "千位定3"
          - "万位定3"

      HIT_RANK_LIST:
        description: "命中排名列表"
        required: false
        default: "[1]"

      LOOKBACK_N:
        description: "回溯期数 0=全部,1=回溯1期"
        required: false
        default: "0"

      ENABLE_SHA1:
        description: "杀号1-策略"
        required: false
        default: "False"

      ENABLE_DAN1:
        description: "定胆1-策略"
        required: false
        default: "False"

      ENABLE_DINGWEI_SHA:
        description: "定位杀号1-策略"
        required: false
        default: "[1]"

      ENABLE_DINGWEI_DAN1:
        description: |
          【定位定胆1】
          策略配置示例：
          [1] = 排行榜第 1 名
          [-1] = 排行榜倒数第 1 名
          ["prev+1"] = 上期开奖号位置 +1 的数字
          ["prev-1"] = 上期开奖号位置 -1 的数字
          ["prev+1,1"] = 上期开奖号下一位，如果无则取第 1 名
          False=不启用
        required: false
        default: "False"


jobs:
  analyze:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 📦 固定最新数据库备份并还原（含进度显示）
        run: |
          echo "=============================="
          echo "🎯 开始执行最新数据库恢复任务"
          echo "⏱ 开始时间: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "=============================="
          START_TIME=$(date +%s)
          
          echo "📁 创建目录"
          mkdir -p data
          
          DOWNLOAD_URL="https://github.com/suwei8/LottoAI3_HitMatrix_date/releases/download/backup-p5/lotto_p5_backup.zip"
          
          echo "✅ 最新下载链接: $DOWNLOAD_URL"
          wget -O data/lotto_backup.zip "$DOWNLOAD_URL"
          
          echo "🔓 解压 ZIP 文件"
          sudo apt-get update && sudo apt-get install -y unzip pv gzip
          unzip -P "$BACKUP_PASSWORD" -o data/lotto_backup.zip -d data/
          
          echo "🚀 恢复数据库（显示导入进度）"
          SQL_GZ_FILE=$(find data -name '*.sql.gz' | head -n 1)
          if [[ -z "$SQL_GZ_FILE" ]]; then
            echo "❌ 未找到 SQL 压缩文件 (*.sql.gz)"
            exit 1
          fi
          
          SQL_FILE_SIZE=$(gzip -l "$SQL_GZ_FILE" | awk 'NR==2 {print $2}')
          
          # ✅ 设置密码，避免警告
          export MYSQL_PWD="$MYSQL_PASSWORD"
          
          # ✅ 强制输出 pv 进度（即使在 GitHub Actions 非交互环境下）
          gunzip -c "$SQL_GZ_FILE" | pv -f -s $SQL_FILE_SIZE | mysql -h$MYSQL_HOST -P$MYSQL_PORT -u$MYSQL_USER $MYSQL_DATABASE
          
          echo "🧹 清理中间文件"
          rm -rf data/*
          
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "=============================="
          echo "✅ 恢复完成：耗时 ${DURATION} 秒（约 $((DURATION / 60)) 分钟）"
          echo "⏱ 结束时间: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "=============================="

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Analysis Batch
        env:
          # === Actions 参数 ===
          CHECK_MODE: ${{ github.event.inputs.CHECK_MODE }}
          DINGWEI_SHA_POS: ${{ github.event.inputs.DINGWEI_SHA_POS }}
          QUERY_PLAYTYPE_NAME: ${{ github.event.inputs.QUERY_PLAYTYPE_NAME }}
          ANALYZE_PLAYTYPE_NAME: ${{ github.event.inputs.ANALYZE_PLAYTYPE_NAME }}
          HIT_RANK_LIST: ${{ github.event.inputs.HIT_RANK_LIST }}
          LOOKBACK_N: ${{ github.event.inputs.LOOKBACK_N }}
          ENABLE_SHA1: ${{ github.event.inputs.ENABLE_SHA1 }}
          ENABLE_DAN1: ${{ github.event.inputs.ENABLE_DAN1 }}
          ENABLE_DINGWEI_SHA: ${{ github.event.inputs.ENABLE_DINGWEI_SHA }}
          ENABLE_DINGWEI_DAN1: ${{ github.event.inputs.ENABLE_DINGWEI_DAN1 }}

        run: python scripts/run_p5.py
        # run: python scripts/run_p5.py > /dev/null 2>&1

      - name: Organize log into folder
        run: |
          mkdir -p log/p5
          mv log/run_p5_*.log log/p5/

      - name: Push logs to private repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          cd log
          git init
          git remote add origin https://suwei8:${{ secrets.PRIVATE_REPO_PAT }}@github.com/suwei8/lotto_ai3_v2-Actions-Analysis-Logs.git

          git checkout -b logs-branch

          # 拉远程最新
          git pull origin logs-branch --allow-unrelated-histories || echo "⚠️ 首次没有远程分支可拉"

          git add .
          git commit -m "🤖 日志推送 RUN_${{ github.run_number }} $(date '+%Y-%m-%d %H:%M:%S')"

          git push origin logs-branch
