# config/fixed/3d/gewei/sha_1.yaml
#  独立玩法推荐取值策略配置
# === 定位杀号位置 ===
DINGWEI_SHA_POS: 0

QUERY_PLAYTYPE_NAME: 定位5*5*5-百位
ANALYZE_PLAYTYPE_NAME: 定位5*5*5-百位

# === 回溯期数 ===
LOOKBACK_N: 1

# === 命中条件 ===
HIT_RANK_LIST: [1]

# === 取值配置 ===
ENABLE_DINGWEI_SHA: [10]